@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Strict data sanitization for forms and favicon 404"
echo Pushing...
git push origin main
echo Done.
