@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Checking status before add...
git status
echo Adding all files...
git add .
echo Checking status after add...
git status
echo Committing...
git commit -m "Update: Fix pending changes and improve modularization"
echo Pushing...
git push origin main
echo Done.
