@echo off
echo Setting PATH...
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Checking git version...
git --version
echo Adding files...
git add .
echo Committing...
git commit -m "Update: Modularization and improvements"
echo Pushing...
git push origin main
echo Done.
