@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Add error handling to startup"
echo Pushing...
git push origin main
echo Done.
