@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Update: New visual identity and form fields order"
echo Pushing...
git push origin main
echo Done.
