@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "UI: Update Plano table columns and expiration logic"
echo Pushing...
git push origin main
echo Done.
