@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Auth token refresh error and dashboard KPI rendering"
echo Pushing...
git push origin main
echo Done.
