@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "UI: Modern Dashboard with new cards and charts"
echo Pushing...
git push origin main
echo Done.
