@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Missing closing style tag causing blank screen"
echo Pushing...
git push origin main
echo Done.
