@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Enable action buttons via event delegation"
echo Pushing...
git push origin main
echo Done.
