@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "Fix: Modal visibility and closing issue"
echo Pushing...
git push origin main
echo Done.
