@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd
echo Adding files...
git add .
echo Committing...
git commit -m "UI: Add toggle for patient form, action icons, and details view"
echo Pushing...
git push origin main
echo Done.
